using System;
using System.Collections.ObjectModel;
using System.Linq;

namespace Blocks.Models
{
    public class WordCollection
    {
        private const string WordList = "ABOUT,ABOVE,ABUSE,ACUTE,ADMIT,ADOPT,ADULT,AFTER,AGAIN,AGENT,AGREE,AHEAD,ALIVE,ALLOW,ALOFT,ALONE,ALONG,ALOOF,ALOUD,ALTER,AMISS,AMONG,ANGER,ANGRY,APART,APPLE,APPLY,APTLY,ARGUE,ARISE,ASIDE,ASKEW,AUGHT,AVOID,AWARD,AWARE,AWFUL,BADLY,BASIC,BASIS,BEACH,BEAST,BEGIN,BELOW,BIRTH,BLACK,BLAME,BLESS,BLIND,BLOCK,BLOOD,BOARD,BRAIN,BRAVE,BREAD,BREAK,BRIEF,BRING,BROAD,BROWN,BUILD,BURST,BUYER,CARRY,CATCH,CAUSE,CHAIN,CHAIR,CHEAP,CHECK,CHEST,CHIEF,CHILD,CHOOK,CIVIL,CLAIM,CLASS,CLEAN,CLEAR,CLIMB,CLOCK,CLOSE,COACH,COAST,COUNT,COURT,COVER,COYLY,CRAZY,CREAM,CRIME,CROSS,CROWD,CROWN,CYCLE,DAILY,DANCE,DEATH,DEPTH,DILDO,DIMLY,DIRTY,DITTO,DOUBT,DRAFT,DRAMA,DREAM,DRESS,DRINK,DRIVE,DRYLY,EARLY,EARTH,EMPTY,ENEMY,ENJOY,ENTER,ENTRY,EQUAL,ERROR,EVENT,EXACT,EXIST,EXTRA,FAINT,FAITH,FALSE,FAULT,FEAST,FIELD,FIFTH,FIGHT,FINAL,FIRST,FLOOR,FOCUS,FORCE,FORTH,FRAME,FRESH,FRONT,FRUIT,FUDGE,FUNNY,GIANT,GLASS,GODLY,GOLLY,GRAND,GRANT,GRASS,GREAT,GREEN,GROSS,GROUP,GUESS,GUIDE,HAPPY,HARSH,HAVOC,HEART,HEAVY,HELLO,HENCE,HORSE,HOTEL,HOUSE,HUMAN,ICILY,IDEAL,IMAGE,IMPLY,INDEX,INNER,INPUT,ISSUE,JOINT,JOLLY,JUDGE,KNIFE,LARGE,LAUGH,LAYER,LEARN,LEAST,LEAVE,LEGAL,LEVEL,LIGHT,LIMIT,LOCAL,LOOSE,LOWLY,LUCKY,LUNCH,MADLY,MAGIC,MAJOR,MARCH,MARRY,MATCH,MAYBE,MERCY,METAL,MINOR,MINUS,MODEL,MONEY,MONTH,MORAL,MOTOR,MOUTH,MUSIC,NAKED,NASTY,NAVAL,NEVER,NEWLY,NIGHT,NOISE,NORTH,NOVEL,NURSE,OCCUR,ODDLY,OFFER,OFTEN,ORDER,OTHER,OUGHT,OUTER,OWNER,PANEL,PAPER,PARTY,PEACE,PHASE,PHONE,PIANO,PIECE,PILOT,PITCH,PLACE,PLAIN,PLANE,PLANT,PLATE,PLONK,PLUMB,POINT,POUND,POWER,PRESS,PRICE,PRIDE,PRIME,PRIOR,PRIZE,PROOF,PROUD,PROVE,PSYCH,QUEEN,QUEER,QUICK,QUIET,QUITE,RADIO,RAISE,RAMEN,RANGE,RAPID,RATIO,REACH,READY,REFER,RELAX,REPLY,RIGHT,RIVER,ROUGH,ROUND,ROUTE,ROYAL,RUGBY,RURAL,SADLY,SALVE,SCALE,SCENE,SCOPE,SCORE,SENSE,SERVE,SHALL,SHAPE,SHARE,SHARP,SHEEP,SHEER,SHEET,SHIFT,SHIRT,SHOCK,SHOOT,SHORT,SHYLY,SIGHT,SILLY,SINCE,SIXTH,SKILL,SLASH,SLEEK,SLEEP,SLYLY,SMALL,SMART,SMILE,SMITH,SMOKE,SNIFF,SOLID,SOLVE,SORRY,SOUND,SOUTH,SPACE,SPARE,SPEAK,SPEED,SPEND,SPITE,SPLIT,SPORT,SQUAD,STAFF,STAGE,STAND,START,STATE,STEAM,STEEL,STEEP,STICK,STILL,STOCK,STONE,STORE,STUDY,STUFF,STYLE,SUGAR,SUPER,SWEET,TABLE,TASTE,TEACH,THANK,THEME,THERE,THICK,THING,THINK,THIRD,THROW,TIGHT,TITLE,TODAY,TOTAL,TOUCH,TOUGH,TOWER,TRACK,TRADE,TRAIN,TREAT,TREND,TRIAL,TRULY,TRUST,TRUTH,TWICE,UNCLE,UNDER,UNION,UNITY,UNTIL,UPPER,UPSET,URBAN,USUAL,UTTER,VAGUE,VALID,VALUE,VIDEO,VIOLA,VISIT,VITAL,WASTE,WATCH,WATER,WHERE,WHICH,WHILE,WHITE,WHOLE,WOMAN,WORLD,WORRY,WOULD,WRITE,WRONG,WRYLY,YEAST,YOUNG,YOUTH";

        public Collection<string> Words { get; set; }

        public WordCollection()
        {
            Words = new Collection<string>(WordList.Split(',').ToList());
        }

        public string GetRandomWord()
        {
            Random random = new Random();
            int next = random.Next(0, Words.Count - 1);

            return Words[next];
        }
    }
}
